---
title: "Random Forest Classifer"
author: "Mervin M Fansler"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document: 
    code_folding: show
    toc: true
    toc_float: true
---

# Purpose

We use a random forest model to classify gene into localization categories.

# Initialization

## Libraries
```{r libs, message=FALSE, warning=FALSE}
library(magrittr)
library(tidyverse)
library(ggtern)
library(broom)
library(caret)
library(randomForest)
library(readxl)
library(writexl)
```

## Parameters
```{r set_params}
set.seed(20220607)
N_STEPS=500

RDS_IN="data/df_tiger_clean.Rds"

LOC_COLORS=c("ER"="#4B74A6", "TG"="#E4E4CA", "CY"="#949494", "DF"="#CCCCCC")
LOC_COLORS_DARK=c("ER"="#4B74A6", "TG"="#C9C497", "CY"="#949494", "DF"="#CCCCCC")

COVARIATES=c(
    "Leb_HuR_CLIP", 
    "Muk_HuR_CLIP", 
    "CPE_annoUTR", 
    "CCCCCC_3UTR_num",
    "Pumilio_3UTR_num", 
    "PUM2_CLIP", 
    "KHSRP_CLIP", 
    "CPSF6_CLIP", 
    "TIS11B_CLIP", 
    "TIA1_L1_CLIP", 
    "PTBP1_CLIP", 
    "HNRNPC_CLIP",
    "CELF2_CLIP", 
    "HNRNPM_CLIP", 
    "HNRNPD_CLIP", 
    "Zhang_RBM15_RIP",
    "LIN28B_CLIP", 
    "IGF2BP3_CLIP", 
    "TARDBP_CLIP", 
    "TAF15_CLIP",
    "FUS_CLIP", 
    "METAP2_CLIP", 
    "DDX6_CLIP", 
    "EIF4A3_CLIP",
    "LARP4B_exon_CLIP", 
    "hnRNPK_CLIP", 
    "GEMIN5_CLIP", 
    "CSTF2T_CLIP",
    "DDX24_CLIP", 
    "PCBP2_CLIP", 
    "PUM_RIP12",
    "Anno_3UTR_length")
```

# Data
## Loading
```{r load_data, message=FALSE}
df_tiger <- readRDS(RDS_IN)
```

## Preprocessing
### Subset
```{r prepare_data}
df_data <- select(df_tiger, category, all_of(COVARIATES))
```

### Imputing
```{r data_impute}
df_imputed <- df_data %>%
    mutate_at("Anno_3UTR_length", ~ ifelse(is.na(.x), median(.x, na.rm=TRUE), .x)) %>%
    mutate_at(-1, ~ ifelse(is.na(.x), 0, .x))
```

### Splitting
```{r data_split}
idx_train <- createDataPartition(df_imputed$category, p=0.8, list=FALSE)

df_train <- df_imputed[idx_train,]
df_test  <- df_imputed[-idx_train,]

full_join(count(df_train, category, name="n_train"),
          count(df_test, category, name="n_test"),
          by="category") %>%
    knitr::kable()
```

# Analysis
## Random Forest Model
### Fit
```{r fit_model}
rf <- randomForest(category ~ ., data=df_train, importance=TRUE)
rf
```
## Model Accuracy
### Train
```{r}
confusionMatrix(predict(rf), df_train$category)
```

### Test
```{r}
confusionMatrix(predict(rf, newdata=df_test), df_test$category)
```

## Importance
```{r feature_importance} 
importance(rf) %>% 
    as_tibble(rownames="feature") %>%
    arrange(-MeanDecreaseAccuracy) %>%
    knitr::kable()
```

---

# Runtime Details
## Session Info
```{r sesh_info, echo=FALSE}
sessionInfo()
```

## Conda Environment
```{bash comment="", echo=FALSE}
if ! command -v conda &> /dev/null
then
  echo "Conda not detected."
elif [ -z "${CONDA_PREFIX}" ]
then
  echo "No active Conda environment."
else
  echo "## Conda Environment YAML"
  conda env export
fi
```
